FROM node:16-alpine

WORKDIR /synapse/src


COPY ./package.json ./
RUN yarn install
COPY ./ ./

ENV PRODUCTION=true
ENV SERVICE_NAME=mongo
ENV ENV_NAME=prod
ENV APP_NAME=synapse

RUN npm run build:mesh

EXPOSE 6868

CMD ["npm", "run", "start-apollo"]