FROM node:16-alpine

WORKDIR /synapse/src


COPY ./ ./
# COPY ./package.json ./
RUN rm -rf node_modules
# RUN npm install --save-dev node
RUN yarn install

ENV PRODUCTION=true
ENV SERVICE_NAME=mongo
ENV ENV_NAME=prod
ENV APP_NAME=synapse

RUN npm run build:mesh

EXPOSE 6868

CMD ["npm", "run", "start-apollo"]
# CMD ["nodemon", "-L", "--watch", ".mesh", "--exec", "npm", "run", "start-apollo"]