FROM node:16-alpine

# RUN mkdir /synapse
# RUN cd synapse
# RUN mkdir src
# RUN useradd -ms /bin/bash newuser
# RUN chown newuser:newuser /synapse/src
# USER newuser

WORKDIR /synapse/src

# USER node

COPY package.json ./
COPY yarn.lock ./

RUN yarn install

COPY ./ ./

RUN chmod -R 777 /root/

ENV PRODUCTION=true
ENV SERVICE_NAME=mongo
ENV ENV_NAME=prod
ENV APP_NAME=synapse

EXPOSE 4005

CMD ["npm", "run", "start-gui"]